AllCops:
  TargetRubyVersion: 2.2
  DisplayCopNames: true
  Exclude:
    - 'tmp/**/*'

Documentation:
  Enabled: false

Metrics/ClassLength:
  Max: 200

Metrics/MethodLength:
  Max: 23

Metrics/BlockLength:
  Max: 27
  Exclude:
    - 'test/**/*'

Metrics/AbcSize:
  Max: 26

Metrics/LineLength:
  Max: 120

Metrics/CyclomaticComplexity:
  Max: 16

Metrics/PerceivedComplexity:
  Max: 10

Style/EmptyMethod:
  EnforcedStyle: expanded
